### ISSUE TITLE
小程序解包出错

### ISSUE THREAD

**Issue by zeroT6** [biggerstar/wedecode#20]
node:internal/process/promises:391
    triggerUncaughtException(err, true /* fromPromise */);
    ^
TypeError [Error]: wx.onAppShow is not a function
    at vm.js:22839:50948
    at vm.js:22839:51157
    at O (vm.js:4:5879)
    at n (vm.js:4:4681)
    at vm.js:22869:224
    at O (vm.js:4:5879)
    at vm.js:22870:10
    at Script.runInContext (node:vm:148:12)
    at VM.runScript (C:\Users\yu\AppData\Roaming\npm\node_modules\wedecode\node_modules\vm2\lib\vm.js:288:18)
    at VM.run (C:\Users\yu\AppData\Roaming\npm\node_modules\wedecode\node_modules\vm2\lib\vm.js:508:16)

Node.js v20.17.0

**Comment by biggerstar** [comment]
已处理
