### ISSUE TITLE
报错：没有找到包特征文件

### ISSUE THREAD

**Issue by mustime** [biggerstar/wedecode#3]
```sh
     🔶       wxapkg 反编译工具 | wedecode (0.2.7)        🔶     

? [自动判断单包或分包]  - 粘贴反编译的 '文件' 或 '目录'  路径:  
/Users/<xxx>/Library/Containers/com.tencent.xinWeChat/Data/.wxapplet/packages/<xxx>/17
? 请输入输出目录, 默认和输入目录同级:  
 ▶ 当前操作类型: 分包模式

 ▶ 解小程序压缩包成功! 文件总数: 535
 ▶ 当前反编译目标 (主包) : /Users/<xxx>/Library/Containers/com.tencent.xinWeChat/Data/.wxapplet/packages/<xxx>/17/__APP__.wxapkg
 ▶ 当前输出目录:  /Users/<xxx>/Library/Containers/com.tencent.xinWeChat/Data/.wxapplet/packages/<xxx>/17/__OUTPUT__

{
  appConfigJson: 1019,
  appWxss: 0,
  appService: 0,
  pageFrame: 0,
  workers: 0,
  pageFrameHtml: 0
}
❌  没有找到包特征文件
file:///usr/local/lib/node_modules/wedecode/dist/wedecode.js:1417
    const entrys = this.DecompilationModules.entrys || {};
                                             ^

TypeError: Cannot read properties of undefined (reading 'entrys')
    at DecompilationMicroApp.decompileAppJSON (file:///usr/local/lib/node_modules/wedecode/dist/wedecode.js:1417:46)
    at async DecompilationMicroApp.decompileAll (file:///usr/local/lib/node_modules/wedecode/dist/wedecode.js:1821:5)
    at async singlePackMode (file:///usr/local/lib/node_modules/wedecode/dist/wedecode.js:1898:3)
    at async Command.<anonymous> (file:///usr/local/lib/node_modules/wedecode/dist/wedecode.js:1952:7)

Node.js v21.6.1
```

你好，使用 0.2.7 版本的工具对某个小游戏解包提示「没有找到包特征文件」，能帮忙分析一下原因吗？
附 wxpkg 的压缩包链接: https://pan.baidu.com/s/1LCOn5TOeOf9-6wBlgFEL9Q?pwd=4nej 提取码: 4nej

**Comment by biggerstar** [comment]
您反馈的问题已经在  `v0.3.0` 中解决， 该版本增加支持了小游戏的反编译

**Comment by mustime** [comment]
怒赞！可以了
