### ISSUE TITLE
请问运行报错resolveAlias is illegal ReferenceError [Error]: __wxConfig is not defined

### ISSUE THREAD

**Issue by Yin55** [biggerstar/wedecode#8]
_                    _
     __      _____  __| | ___  ___ ___   __| | ___
     \ \ /\ / / _ \/ _` |/ _ \/ __/ _ \ / _` |/ _ \
      \ V  V /  __/ (_| |  __/ (_| (_) | (_| |  __/
       \_/\_/ \___|\__,_|\___|\___\___/ \__,_|\___|

 ▶ 解小程序压缩包成功! 文件总数: 148
 ▶ 反编译 app.json 文件成功.

🎄  当前使用版本:  v0.3.1

 ▶ 当前反编译目标[ 小程序 ] (主包) : C:\Users\yin\Desktop\wxpack\app.wxapkg
 Completed  (14589)     C:\Users\yin\Desktop\wxpack\__OUTPUT__\app.json ▶ 当前操作类型: 分包模式
 ▶ 当前输出目录:  C:\Users\yin\Desktop\wxpack\__OUTPUT__
resolveAlias is illegal ReferenceError [Error]: __wxConfig is not defined
    at vm.js:38:22
    at Script.runInContext (node:vm:133:12)
    at VM.runScript (C:\Users\yin\AppData\Roaming\npm\node_modules\wedecode\node_modules\vm2\lib\vm.js:288:18)
    at VM.run (C:\Users\yin\AppData\Roaming\npm\node_modules\wedecode\node_modules\vm2\lib\vm.js:508:16)
    at DecompilationMicroApp.decompileAppPageJSON (file:///C:/Users/yin/AppData/Roaming/npm/node_modules/wedecode/dist/wedecode.js:1543:8)
    at DecompilationMicroApp.decompileAll (file:///C:/Users/yin/AppData/Roaming/npm/node_modules/wedecode/dist/wedecode.js:1955:18)
    at async singlePackMode (file:///C:/Users/yin/AppData/Roaming/npm/node_modules/wedecode/dist/wedecode.js:2030:3)
    at async Command.<anonymous> (file:///C:/Users/yin/AppData/Roaming/npm/node_modules/wedecode/dist/wedecode.js:2089:7)

node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^
ReferenceError [Error]: __wxConfig is not defined
    at vm.js:39:3313
    at vm.js:39:6124
    at Script.runInContext (node:vm:133:12)
    at VM.runScript (C:\Users\yin\AppData\Roaming\npm\node_modules\wedecode\node_modules\vm2\lib\vm.js:288:18)
    at VM.run (C:\Users\yin\AppData\Roaming\npm\node_modules\wedecode\node_modules\vm2\lib\vm.js:508:16)
    at DecompilationMicroApp.decompileAppPageJSON (file:///C:/Users/yin/AppData/Roaming/npm/node_modules/wedecode/dist/wedecode.js:1543:8)
    at DecompilationMicroApp.decompileAll (file:///C:/Users/yin/AppData/Roaming/npm/node_modules/wedecode/dist/wedecode.js:1955:18)
    at async singlePackMode (file:///C:/Users/yin/AppData/Roaming/npm/node_modules/wedecode/dist/wedecode.js:2030:3)
    at async Command.<anonymous> (file:///C:/Users/yin/AppData/Roaming/npm/node_modules/wedecode/dist/wedecode.js:2089:7)

Node.js v18.20.4

C:\Users\yin\Desktop\wxpack>

**Comment by biggerstar** [comment]
你将 小程序包 邮件发我 或者 发在任意平台能下载就行

**Comment by Yin55** [comment]
> 你将 小程序包 邮件发我 或者 发在任意平台能下载就行

麻烦了
[wxpack.zip](https://github.com/user-attachments/files/16493124/wxpack.zip)

**Comment by biggerstar** [comment]
最新版 `v0.5.0` 已修复该问题

**Comment by Yin55** [comment]
> 最新版 `v0.5.0` 已修复该问题

谢谢
